import pandapower as pp


def get_power_dict():
    """Creates a dictionary of major power system components in a network.
    Used for naming automatically generated networks.

    Returns:
        [dictionary of string: string] -- Mapping of infrastructure component abbreviations to names.
    """
    power_dict = {
        "L" : "Line",
        "B" : "Bus",
        "TF": "Transformer",
        "MP": "Motor",
        "L" : "Load",
        "S" : "Switch",
        'G' : 'Generator'
    }
    return power_dict

def load_power_network(network_json):
    """Loads the power system model from a *.json file.

    Arguments:
        network_inp {string} -- Location of the *.json power system file generated by pandapower package.

    Returns:
        object -- The loaded power system model object.
    """
    pn = pp.from_json(network_json, convert=True)
    print('Power system successfully loaded from {}'.format(network_json))
    return pn


# Simulate power flow
def run_power_simulation(pn):
    """Runs the power flow model for an instance.

    Arguments:
        pn {object} -- A power system model object generated by pandapower package.
    """
    pn_sim = pp.runpp(pn)

